export const SET_CHARACTER = 'SET_CHARACTER';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_FAVORITES = 'SET_FAVORITES';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const DELETE_FAVORITES = 'DELETE_FAVORITES';
export const DELETE_ALL_FAVORITES = 'DELETE_ALL_FAVORITES';
export const GET_CHARACTER = 'GET_CHARACTER';